services:
  dev:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
    command: npm run dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: scale_perform_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: scale_perform
  prometheus:
    image: prom/prometheus
    container_name: scale_perform_prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: scale_perform_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  prod:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"

volumes:
  mongo-data:
    driver: local
